### ISSUE TITLE
Question about "design_desktop.jpg"

### ISSUE THREAD

**Issue by Olow304** [duraanali/html-template-contest#1]
Hi Duraanali, do we have to replicate the exact same page as this template you provide https://github.com/Olow304/html-template-contest/blob/master/design_desktop.jpg, you didn't mentioned anything that we need to replicate on the contest page. You just said "Html css template" contest.

**Comment by Olow304** [comment]
I answered my own question. 👍

**Comment by duraanali** [comment]
lol, yes all of it bro. You turn that image into html and css.
